import type Anthropic from '@anthropic-ai/sdk';

/**
 * External context, from Anthropic's server-side web search.
 *
 * WHY THIS REPLACED BRAVE. The first version called the Brave Search API from
 * our own handler and returned five snippets. It never ran once: the key was
 * never set, so every search the model attempted came back as the string
 * "Web search not configured" and the model wrote its answer without it. The
 * failure was invisible for as long as the feature existed.
 *
 * Brave was reconsidered rather than simply fixed, and lost on the thing that
 * matters most here -- PROVENANCE. Sauron's rule is that every figure comes
 * from a query tool, and an external number breaks it unless the reader can see
 * where it came from. Brave returns a description snippet with no link between
 * any particular number and any particular source, so the attribution would
 * have had to be inferred, by us, from prose. This tool returns CITATIONS: each
 * cited claim carries the url, the page title, and up to 150 characters of the
 * sentence it was taken from. That is the provenance record, supplied rather
 * than reconstructed, and it is the whole reason for the switch. (Brave is also
 * no longer free as of Feb 2026, which removed the other argument for it.)
 *
 * THE FIGURES IT PRODUCES ARE NOT WAREHOUSE FIGURES. Nothing here is
 * reconciled, nothing is about our venues, and a number from a trade blog has
 * no standing beside one Postgres computed. The system prompt says so; the
 * sources returned alongside the answer are what let a reader check.
 */

/**
 * Which version, and why this one.
 *
 * `web_search_20260209` adds dynamic filtering -- the model writes code that
 * filters results before they reach the context window, so a search costs far
 * fewer tokens than dumping five pages in. It is supported on Sonnet 5 (what we
 * run today) and Opus 5 (where the analysis path is heading).
 *
 * `web_search_20260318` exists and adds `response_inclusion`, which can drop
 * raw search blocks from the response to save output tokens. Not used: we WANT
 * those blocks, because they are how a search failure becomes visible.
 *
 * If a future model returns 400 asking for `allowed_callers`, that model does
 * not support programmatic tool calling and the fix is
 * `allowed_callers: ['direct']` -- which turns dynamic filtering off, not the
 * search.
 */
export const WEB_SEARCH_TOOL_TYPE = 'web_search_20260209' as const;

/**
 * The container a search's dynamic filtering ran in, which the NEXT request in
 * the same turn has to name.
 *
 * THE BUG THIS FIXES cost three complete Opus analyses. Dynamic filtering is
 * the reason this tool version was chosen -- the model writes code that filters
 * results before they reach the context -- and that code runs in a sandboxed
 * code execution container, provisioned automatically by the API. Once it has
 * run, the assistant message being pushed back carries pending tool uses
 * belonging to that container, and a follow-up request that does not name it is
 * rejected outright:
 *
 *   400 invalid_request_error: container_id is required when there are pending
 *   tool uses generated by code execution with tools.
 *
 * So it is not optional and not an optimisation -- an agentic loop that
 * searches the web and then runs one more tool round CANNOT work without it.
 * The recommendation engine surfaced it because its brief pushes towards
 * external context, so all three venues searched; the chat has the same hole
 * on any question that searches and then queries again.
 *
 * Deliberately NOT handled by `isWebSearchConfigError()` and a retry without
 * the tool. That fallback exists for a tool definition the API refuses, where
 * dropping the feature is the right degradation. Here the search SUCCEEDED and
 * its results are already in `messages`; the request is simply incomplete.
 * Dropping the tool at that point fails for a different reason, which is
 * exactly what the comment on `searchDisabled` already warns about.
 *
 * Returns the current id when a response carries none, because only some
 * responses in a turn create or reference a container and the id must survive
 * the rounds in between.
 */
export function nextContainerId(current: string | null, response: unknown): string | null {
  const container = (response as any)?.container;
  const id = container && typeof container.id === 'string' ? container.id : null;
  return id ?? current;
}

/**
 * Whether a 400 is the missing-container error.
 *
 * Recognised so it can be REPORTED as itself rather than as a generic failure.
 * There is no useful retry: by the time it is thrown the request was built
 * without an id we did not have, and the fix is upstream.
 */
export function isMissingContainerError(e: any): boolean {
  if (e?.status !== 400) return false;
  const detail = typeof e?.message === 'string' ? e.message : JSON.stringify(e ?? {});
  return /container_id is required/i.test(detail);
}

/**
 * A hard ceiling on searches per request, enforced by Anthropic rather than by
 * asking the model nicely.
 *
 * Five is chosen against the documented behaviour: a simple factual lookup uses
 * one to three, comparative research can use ten or more. Five allows a real
 * question and refuses a runaway. At $10 per 1,000 searches that caps the
 * search cost of any one question at five cents, which is the point -- the
 * Brave alternative was a card with no spending cap behind a tool the model can
 * call in a loop.
 */
export const MAX_SEARCHES_PER_REQUEST = 5;

/**
 * Singapore, because every venue is here and search results are localised.
 *
 * "Public holidays next month", "what is opening nearby", "is there a
 * convention on" all return a different and mostly useless web without this.
 *
 * NO `country`, AND THAT IS NOT AN OVERSIGHT. `country: 'SG'` was set first --
 * the field is documented as an ISO 3166-1 alpha-2 code and SG is a valid one
 * -- and the API rejected it outright:
 *
 *   400 invalid_request_error: tools.12.web_search_20260209:
 *   Country code SG is not supported.
 *
 * Anthropic supports a subset and does not publish which, so a valid code is
 * not necessarily an accepted one and no amount of reading finds out. The docs
 * require at least one of city, region, country or timezone, so the other two
 * carry the localisation on their own.
 *
 * Do not add `country` back without testing it against the live API first.
 */
export const SEARCH_LOCATION = {
  type: 'approximate' as const,
  city: 'Singapore',
  timezone: 'Asia/Singapore',
};

/**
 * The tool definition sent with every request.
 *
 * `allowed_domains` is deliberately NOT set. It is the strongest guardrail
 * available here -- restrict searches to sources somebody has vetted and "a
 * blog said 30%" stops being possible -- but it is the wrong control for
 * general context like holidays and local events, which is most of what this
 * is for. It belongs on the benchmarks path, where an external NUMBER is the
 * point, not here.
 */
export function webSearchTool(): Anthropic.Messages.WebSearchTool20260209 {
  return {
    type: WEB_SEARCH_TOOL_TYPE,
    name: 'web_search',
    max_uses: MAX_SEARCHES_PER_REQUEST,
    user_location: SEARCH_LOCATION,
  };
}

/**
 * Is this the API refusing our web search TOOL DEFINITION, rather than
 * refusing the question?
 *
 * WHY THIS EXISTS. `country: 'SG'` was rejected with a 400, and because the
 * tool is sent on every request, EVERY question failed -- including "what were
 * net sales yesterday", which needs no web search at all. The whole chat went
 * down, in front of a user, over a field that only matters for holidays and
 * local events.
 *
 * That is the wrong failure mode and the codebase already has the right one
 * written down: warnSchema logs and carries on where requireSchema exits,
 * because a degraded app beats a dead one. A misconfigured optional tool must
 * cost the feature, never the product.
 *
 * Deliberately narrow -- a 400 that names web_search. A 400 about the messages
 * array is our bug and should surface, not be quietly retried.
 */
export function isWebSearchConfigError(e: any): boolean {
  const status = e?.status ?? e?.response?.status;
  if (status !== 400) return false;
  let detail = '';
  try {
    detail = `${e?.message ?? ''} ${JSON.stringify(e?.error ?? {})}`;
  } catch {
    detail = String(e?.message ?? '');
  }
  return /web_search/i.test(detail);
}

/**
 * The answer's text, reassembled from its blocks.
 *
 * JOINED WITH NOTHING, and the separator is the entire point. Without
 * citations a reply arrives as a single text block, so joining with "\n" was
 * invisible for months. Citations split the message: a cited span becomes its
 * own block, so one paragraph arrives as three or four. Joining those with a
 * newline breaks sentences mid-clause and strands the punctuation that followed
 * a citation on a line of its own --
 *
 *   The one day-specific forecast I found
 *   put 20 August at a high around 31°C
 *   . Broader seasonal context:
 *
 * -- which is what the first cited answer actually looked like. The blocks are
 * fragments of one continuous message, not paragraphs, and the model's own
 * newlines are already inside them.
 */
export function joinText(content: Anthropic.Messages.ContentBlock[]): string {
  return content
    .filter(b => b.type === 'text')
    .map(b => (b as Anthropic.Messages.TextBlock).text)
    .join('');
}

/** One external page the answer actually cited, with every passage it used. */
export interface WebSource {
  url: string;
  title: string | null;
  /**
   * Each distinct passage drawn from this page, up to 150 characters apiece.
   *
   * A LIST, not one string, and grouped by page rather than one entry per
   * quote. The first version emitted a row per citation, so an answer built on
   * a single government forecast rendered the same link seven times -- the
   * noise this was meant to avoid, in a new place. Merging the QUOTES too would
   * be worse: it would leave one passage standing behind a claim it does not
   * support. So the link collapses and the evidence does not.
   */
  quotes: string[];
}

/** Fold sources for the same url together, preserving quote order. */
export function mergeSources(sources: WebSource[]): WebSource[] {
  const byUrl = new Map<string, WebSource>();

  for (const source of sources) {
    const existing = byUrl.get(source.url);
    if (!existing) {
      byUrl.set(source.url, { ...source, quotes: [...source.quotes] });
      continue;
    }
    // A page cited once with a title and once without keeps the title.
    if (!existing.title && source.title) existing.title = source.title;
    for (const quote of source.quotes) {
      if (!existing.quotes.includes(quote)) existing.quotes.push(quote);
    }
  }

  return [...byUrl.values()];
}

/**
 * The sources behind an answer, taken from the citations on its text blocks.
 *
 * Read from CITATIONS rather than from the search result blocks, and the
 * difference matters: result blocks list everything the search returned,
 * citations list what the answer actually leaned on. A reader checking a claim
 * wants the second. It is also the stable place to read from -- with dynamic
 * filtering the result blocks are nested inside code-execution output and carry
 * a `caller` field, while citations stay attached to the text either way.
 *
 * Deduplicated by url + quote, because the model cites the same passage more
 * than once in a paragraph and a list of six identical links is noise.
 */
export function extractSources(content: Anthropic.Messages.ContentBlock[]): WebSource[] {
  const sources: WebSource[] = [];

  /**
   * Walks NESTED blocks, not just the top level.
   *
   * Dynamic filtering runs the search from inside code execution, and the docs
   * are explicit that the nested server_tool_use and web_search_tool_result
   * pairs arrive inside the code execution result rather than beside it.
   * searchErrors() was written that way and this was not -- the same response,
   * read two different ways, in one file.
   *
   * Whether the model's own citations can nest is not something the docs
   * settle. Walking anyway costs nothing and removes the question.
   */
  const visit = (blocks: any[]): void => {
    for (const block of blocks) {
      if (!block || typeof block !== 'object') continue;

      if (block.type === 'text') {
        for (const citation of block.citations ?? []) {
          if (citation.type !== 'web_search_result_location') continue;
          sources.push({
            url: citation.url,
            title: citation.title,
            quotes: [citation.cited_text],
          });
        }
        continue;
      }

      if (Array.isArray(block.content)) visit(block.content);
    }
  };

  visit(content as any[]);

  // Grouping and de-duplication both live in mergeSources, so one page cited
  // twice in a paragraph and one page cited across two responses collapse the
  // same way.
  return mergeSources(sources);
}

/**
 * Pages the search RETURNED, whether or not the answer quoted any of them.
 *
 * A weaker record than a citation and a much better one than nothing. Two runs
 * of the recommendation engine performed seven searches between them and
 * produced zero citations, which left no trace at all of what had been looked
 * at -- so a reader could not tell whether the search had found nothing,
 * returned something the model ignored, or informed the answer silently.
 *
 * Citations say "this sentence came from here". This says "these pages were in
 * front of it". They are different claims and the app should show them
 * differently.
 */
export function consultedPages(content: Anthropic.Messages.ContentBlock[]): Array<{ url: string; title: string }> {
  const pages = new Map<string, string>();

  const visit = (blocks: any[]): void => {
    for (const block of blocks) {
      if (!block || typeof block !== 'object') continue;

      if (block.type === 'web_search_tool_result') {
        // A list is results; a single object is the error case, handled by
        // searchErrors().
        if (Array.isArray(block.content)) {
          for (const result of block.content) {
            if (result?.type === 'web_search_result' && typeof result.url === 'string') {
              if (!pages.has(result.url)) pages.set(result.url, result.title ?? result.url);
            }
          }
        }
        continue;
      }

      if (Array.isArray(block.content)) visit(block.content);
    }
  };

  visit(content as any[]);
  return [...pages].map(([url, title]) => ({ url, title }));
}


/**
 * Search failures, which do NOT arrive as failures.
 *
 * A rate-limited or errored search returns HTTP 200 with an error object where
 * the results should be -- so from the outside it is indistinguishable from a
 * search that found nothing, and the model writes a confident answer with no
 * external context in it. That is the same shape as the Brave key never being
 * set, which went unnoticed for the life of the feature, so it is pulled out
 * and reported rather than left to be inferred.
 *
 * `error_code` is one of too_many_requests, invalid_tool_input,
 * max_uses_exceeded, query_too_long, request_too_large, unavailable. An empty
 * result list is NOT an error -- it means the search ran and matched nothing.
 */
export function searchErrors(content: Anthropic.Messages.ContentBlock[]): string[] {
  const errors: string[] = [];

  const visit = (blocks: any[]): void => {
    for (const block of blocks) {
      if (!block || typeof block !== 'object') continue;

      if (block.type === 'web_search_tool_result') {
        const inner = block.content;
        // A list is results; a single object is the error case.
        if (inner && !Array.isArray(inner) && inner.type === 'web_search_tool_result_error') {
          errors.push(String(inner.error_code ?? 'unknown'));
        }
        continue;
      }

      // Dynamic filtering runs the search from inside code execution, so the
      // result blocks arrive nested rather than at the top level.
      if (Array.isArray(block.content)) visit(block.content);
    }
  };

  visit(content as any[]);
  return errors;
}

/** How many searches Anthropic actually billed for this response. */
export function searchRequestCount(usage: Anthropic.Messages.Usage | undefined): number {
  return usage?.server_tool_use?.web_search_requests ?? 0;
}

/**
 * What the model is told about external figures.
 *
 * This is a hint, not a control, and is written knowing that. The controls are
 * elsewhere: `max_uses` is enforced by Anthropic, and the citations returned
 * beside the answer let a reader check any external claim without trusting the
 * model to have labelled it. This closes the common case, where the model would
 * otherwise set a number it read on a blog beside one Postgres computed and
 * give them the same standing.
 */
export const EXTERNAL_CONTEXT_FRAMING = `
YOU MUST SEARCH THE WEB BEFORE STATING ANY FACT ABOUT THE WORLD OUTSIDE OUR OWN DATA. Holiday dates, school terms, local events, industry benchmarks, competitor news, weather, opening hours, prices — you do not know these reliably. Your knowledge has a cutoff, dates shift, and figures are revised. Search first, then answer from what the search returned.

Do not answer such a question from memory even when you feel certain, and do not treat a date as safe because it is "well known" — asked for Singapore's 2026 public holidays without searching, you would state eleven dates and get the moon-sighting ones wrong while sounding entirely confident. If a search returns nothing usable, say the fact is unverified. Never present a remembered date or figure as established.

Web search is for EXTERNAL context only: industry benchmarks, Singapore public holidays and local events, F&B trends, weather, competitor news. Never use it for anything about this business — every figure about our own venues comes from a query tool.

A number from the web and a number from the warehouse are not the same kind of thing, and must never be presented as though they were:
- A warehouse figure is OUR data, reconciled. State it plainly.
- A web figure is somebody else's claim about somebody else's business. Name the source in the sentence that uses it — "a 2026 industry survey puts casual dining food cost near 30%" — never a bare "the industry average is 30%".
- Never do arithmetic that mixes the two into a single number. Say "ours is 32%, that survey says 30%" and let the reader make the comparison; do not report "2 points above industry" as if it were a measured figure.
- If a search returns nothing useful, say so. Do not fill the gap from memory — a remembered benchmark is exactly the hallucination this system exists to prevent.`;
